POST http://localhost:8001/account/change-password HTTP/1.1
content-type: application/json
Cookie: state=MTY5MDg2NzQ2M3xGcUtFNHdVRGs2bVM2NWJnTTNJWXNULVZQWmQ2U2ZaSjg1MmV3NE5uRVZIY3psRkM4UElMbUE1YkVQMlhUTGx5WlhMOUtWMWtUdEFEY1ZCREtWS2J6ZWJWLUZiem1Ld3hrMGhrT210UkZoeC15alQzVU82VXQxS1dXU292QU1DV3JrTnRVTlpTNFlWU1Yyc1lDLXluWDVNOE1TTlZyMW9pTkJoTnltc3VzTF9QaXBsTjFCZ1FTcTBWWVZJOEs0ZFNpY1haVURMcXFOTm1RR1RkM2xkTlJLRGJnTy1GX1NiVkhoZjMtenB5VDY3Sk8tVjZKeHhpeUlocVlpTzFvckk0d0pOTUpTOUk3V2Z0TWxBWkREWHpkMHNIcU9BVnBzUnBTei1zWFk5ZWFkWmJycUNSTV81TUtNOEdNZW1JQVFhVk1MM3FFb04zQlBQTHU4blhXZE05TTF1bW5uU2Y0SmY3Nmo4elVUR1k2WjBEUEtJRXRrWnRMc1BWYWE1QWd6NnhLajhfU2U0OGtERmowTUpKUUhOOHJ5RURkdzVLRTRRNXFjRVphaUpJcnN4UjFfR3Q1VkJydXpSLThxbG9PQ2E5M0NZOUtoWlNmOUlZWWRsVE1pNXU2UlVZfEG-XVGi5wPXNEkBDXRNPX69S7aSUb9Pji4N3HRKgncz; Path=/; HttpOnly; Secure

{
    "id": "01H6P8AVE3KPPB7F396SVKAHJC"
}
