POST http://localhost:8001/account/change-password HTTP/1.1
content-type: application/json
Cookie: state=MTY5MDkwNDM5OHx0UF91TUdfdG9zN1daRVdmZzdOOE1zMldGRG5zVHQ5XzUyNjRFc2VxeXFDOXp6d3NvYWZ0QklnNjZRdFpPMExRMHlKUlY1NlpGSEMzU2J1M2N1d3diN2ZxREhlSGVaLUllMEFYM09ZWTN5MXNVZDdDUVpUZkc1bUlfQTBheDZwbG52aVNTRzRoMDhZeGdBdGk0d2hYaHZoNTBSNkRFVkdJbml2RENWT2FrcDlpYW85b1gxVEV4b3FPX08taFdOZ0VoanlwblUxVnJTMHpGSlU0VFhoVVVqaTZKcnZUSWJyWko3Ykp2SFZJS0k5QTZZdE4wbWhWSW1JVU5KbTlxUkM1YWFsZ1RacUxaaG1KcHk2ZlJTNTA5dnRCX3NrN3ZvZFNNYkNyTHhJNHJZUC1TWHF5eHJOQU9rRTBNT0ZlcXlicjlnY0FEV3lacVAzUGRONGdkamlEc3RpdzlLRzl3SnRTdGgycDZnTnFqakE4Z1RnMU8wS1N0WXVScnZvWmZuWWxZV0VZSm9vOENZYy1FYUNTYVlKcXNUVG5CVUloRDkybHpoYmVKZ0dNTW9FZ0RvS0kxV3p6MlVTN2RVcG92R24xWFNubWZMcS1vMzItQ1pVUUlKbEhRekQzfPsO7tsEWZ9Ir3MpM3MuZjo647zOrBpOOkO8UlKIhxf0; Path=/; Expires=Tue, 01 Aug 2023 15:44:58 GMT; HttpOnly; Secure

{
    "id": "01H6P8AVE3KPPB7F396SVKAHJC"
}
